### PR TITLE
add :class.class-name=... :style.style-name=... supported

### PR DESCRIPTION
**Pull request by Funlang**
:class.class-name=...
:style.style-name=...

### CODE REVIEW

**Comment by Funlang** [comment]
for performance

**Comment by Funlang** [comment]
for performance

**Comment by aidenybai** [comment]
How is this more performant? Is this feature necessary? Why did you feel the need to add `// added by zwd@funlang.org @2021-04-08 for performance` for each of your commits?

**Comment by Funlang** [comment]
- performance for this issue, https://github.com/alpinejs/alpine/issues/566
- comments in code will be deleted
- :class.xxx.xxx will be supported for modify a little code: modifiers.forEach(....

**Comment by KevinBatdorf** [comment]
Just a tip (I know you're still working on the PR), if you're making performance improvements you'll want to show off a measurement of the improvement with a way for others to interact with.

**Comment by Funlang** [comment]
In this test, https://codepen.io/funlang/pen/BapwWpP, it will be completed in 3s improved from 10s+.

- The mutations have 20,000+ childList, so the loop is so slow, changed to query x-data from the root run at once, it improve immediatelly.

**Comment by Funlang** [comment]
In this benchmark https://krausest.github.io/js-framework-benchmark/2021/table_chrome_89.0.4389.72.html

- AlpineJs' score is not good, so I want to do some improvement

**Comment by HugoDF** [comment]
@Funlang would probably be a good idea to do each perf improvement as a separate PR

**Comment by Funlang** [comment]
> @Funlang would probably be a good idea to do each perf improvement as a separate PR

Thanks that is a good idea, but I don't know how to do that.

**Comment by HugoDF** [comment]
> > @Funlang would probably be a good idea to do each perf improvement as a separate PR
> 
> Thanks that is a good idea, but I don't know how to do that.

You'll need a branch for each perf improvement, then you can open a PR from each of the branches into Alpine

**Comment by Funlang** [comment]
> > > @Funlang would probably be a good idea to do each perf improvement as a separate PR
> > 
> > 
> > Thanks that is a good idea, but I don't know how to do that.
> 
> You'll need a branch for each perf improvement, then you can open a PR from each of the branches into Alpine

thanks, I will study to do that

**Comment by Funlang** [comment]
> > > @Funlang would probably be a good idea to do each perf improvement as a separate PR
> > 
> > 
> > Thanks that is a good idea, but I don't know how to do that.
> 
> You'll need a branch for each perf improvement, then you can open a PR from each of the branches into Alpine

Thanks so much for your help, I think I learned to work on github ;-)

**Pull request closed without merging**
