### PR TITLE
fix: set custom properties in style correctly

### PR DESCRIPTION
**Pull request by pohlt**
This fixes the issue mentioned here: https://github.com/alpinejs/alpine/discussions/1807

@KevinBatdorf Thanks for the initial bugfix. Could you please have a look?

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
You probably want to test the surrounding functionality too, specifically this line.

```js
previousStyles[key] = el.style[key]
```
https://github.com/alpinejs/alpine/pull/1854/files#diff-0cbf36cdc048c0c051e4a96236cc2dd86fb1028070bc58f5ab620256ec4d60ecR14

Does it preserve the custom property? Does it need to be converted to `.getPropertyValue` maybe (I haven't looked, so maybe not)?

**Comment by pohlt** [comment]
I added another test. Does that cover the case you had in mind?

**Comment by pohlt** [comment]
Works in my fork: https://github.com/pohlt/alpine/runs/3162656086

**Comment by KevinBatdorf** [comment]
Yeah I think that was worth adding. But wait and see what Caleb says.

**Comment by pohlt** [comment]
@KevinBatdorf You don't happen to have the rights to start the test workflow?

**Comment by KevinBatdorf** [comment]
What do you mean? To run the tests? They should run when you commit. You can remove you change so the tests fail, the commit the change again so they pass.

Is that what you mean?

I don't have any repo/org privledges though. I just try to help where I can.

**Comment by pohlt** [comment]
I get this message as a last  entry in this PR
image
...so I was wondering if you could give your approval, but you don't seem to have the required rights. Thanks anyway.

**Comment by KevinBatdorf** [comment]
Ah dang. I haven't seen that before either.

**Comment by calebporzio** [comment]
Interesting re: needing approval to run. It appears this is a new default for GitHub. I changed the setting to be more lenient, although there is no option to simply allow all users to run actions:
image

I imagine this is a result of the recent Actions abuse they've been facing.

You should be good to run actions now

**Comment by calebporzio** [comment]
Anyhow, thanks for this!

**Pull request merged**
