### PR TITLE
x-mask custom decimal precision

### PR DESCRIPTION
**Pull request by Restartz**
Allows for custom decimal precision using x-mask $money magic as requested here: https://github.com/alpinejs/alpine/discussions/2873

Example usage:
- To allow for a decimal precision of 3 digits: `<input x-data x-mask:dynamic="$money($input, '.', ',', 3)">`
- To only allow for round numbers: `<input x-data x-mask:dynamic="$money($input, '.', ',', 0)">`

It defaults to 2, so the current behaviour without specified precision should still be the same:
`<input x-data x-mask:dynamic="$money($input)">`

### CODE REVIEW

**Comment by ekwoka** [comment]
Looks good. Maybe at this point it needs to be made into an options object?

**Comment by Restartz** [comment]
I've changed the $money helper to accept an options object as the second parameter.
So precision can now be set as follows: 
`$money($input, { precision: 3 })`

The delimiter and thousands params can also be passed trough the options object: 
`$money($input, { delimiter: ',', precision: 0 })`

Calls like `$money($input, ',')` or `$money($input, ',', ' ')` also still work.

**Comment by calebporzio** [comment]
Hey @Restartz, thanks for this. I actually prefer the 4th param instead of the options object. Can you remove all the options object stuff and we'll merge? Thanks!

Oh, and can you also add documentation for this?

**Comment by Restartz** [comment]
@joshhanley Done and done! 🙂

**Comment by joshhanley** [comment]
@Restartz thanks!

**Pull request merged**
