### PR TITLE
Improve changelog capability

### PR DESCRIPTION
**Pull request by nandordudas**
This is an option for creating better changelog documentation. I'm using git-changelog for this purpose most times. And follow conventional committing principles.
You can see the behavior, check commits and the changelog.

### CODE REVIEW

**Comment by nandordudas** [comment]
[conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)
[git-chglog](https://github.com/git-chglog/git-chglog)

and im recommend to using of [git-flow](https://danielkummer.github.io/git-flow-cheatsheet/)

**Comment by nandordudas** [comment]
If you think it useful, then dont forget to add `chore` item to `filters` and `title_maps`.

## DRAFT

Realeasing will be easier - i'm using GitKraken, but there is a cli solution:
- `git-flow release start 2.1.4`,
- do changes and commits,
- `git-flow release finish 2.1.4 -m 'Bum up version to v2.1.4' -p`,
- `git-chglog -o CHANGELOG.md`,
- `git add CHANGELOG.md && git commit --amend --no-edit`,
- copy last relase message from `CHANGELOG.md` and paste it to `Edit tag`.

Committ messages can be validate like your own rules - or you can use mainstream emojis.

**Comment by SimoTod** [comment]
Does the last commit belong to this PR?
It doesn't seem to be related to the change log feature, it will make it harder for Caleb to review.
It's probably a good idea if you can send a separate PR for that (I know, I'm annoying, sorry :))

**Comment by nandordudas** [comment]
Your not, i'm really happy for your response!
I'm so sorry - this will be another PR's content -, can you remove it?
Or i undo my last commit and send it one more time?

**Comment by nandordudas** [comment]
Hehe, nothing happens 😄

**Comment by SimoTod** [comment]
No worries, I don't think I can remove it since it's in your fork but you can do `git reset --hard HEAD^` (this will discard your last commit, make sure you make a copy your utils.js somewhere else) and then `git push -f`. Or just revert the changes here, I think it's okay as well.

**Comment by calebporzio** [comment]
Thanks @nandordudas, but going to stick to doing these by hand for now.

**Pull request closed without merging**
