### PR TITLE
docs: switch unpkg to jsdelivr

### PR DESCRIPTION
**Pull request by ayuhito**
I think it would be appropriate for alpine.js to move away from unpkg since it is unmaintained and [full of issues](https://github.com/mjackson/unpkg/issues). On the other hand, [jsDelivr](https://www.jsdelivr.com/) is actively maintained and uses a more reliable [fallback system](https://www.jsdelivr.com/network/infographic) using multiple CDN networks.

Let me know if there are any concerns!

### CODE REVIEW

**Comment by ekwoka** [comment]
While maybe out of scope with your change, showing how to use `esm.sh` for modules could be a nice addition as well.

**Comment by joshhanley** [comment]
Not as nice url as unpkg, but makes sense, thanks!

**Comment by Igloczek** [comment]
Sorry for digging this up, but, right on the https://alpinejs.dev/ there is still `<script src="//unpkg.com/alpinejs" defer></script>`.

**Comment by ekwoka** [comment]
The homepage is something only @calebporzio can update.

**Pull request merged**
