### PR TITLE
docs(note-show-style-order)

### LINKED ISSUE #434: x-show gets overridden by :style
See [this 2.3.1 example](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8YWACcyAB3gACMKNgBeADogc8CWFQB6LbCR0MAKzBJoZAG6iMdCPC0BzLFoZQJZG8eev3EAALmAJgwAZgwARi0kMjA7FzcbDFx3IzAVAD5BLRFxKTSlOnzBKPN86WkADwBaJAZ4BmUQYGksMlNUaXhRAFcIaQBfFVKKytgobgYAayGqsCxuAHcGgEIW00G6MtQYgE8YBoADHjHRdtFkffW8jekATW4u2TmuqH0AchlIXuZCyIsrzkgMAQZF4VHQADZUAEAiA+oR6EwWOgUpweHwIAJ0LD4SBGMxWBhYGAqMQ0fx4KxqFVRuMJgBdaRNKJgCRQBjbdp0XgQADc-XyAOgcHgILoYJAYVQAAZYXS+kA). The text shows up when it shouldn't. If you delete the `:style` line, or empty its value, or remove the backticks, it works as expected.

### PR DESCRIPTION
**Pull request by HugoDF**
Closes #434

### CODE REVIEW

**Comment by SimoTod** [comment]
I wish we could reconsider https://github.com/alpinejs/alpine/pull/236, to be fair (without the object support if Caleb is not sure). I think it's annoying that x-on:style overrides any values in pre existing style attributes.

**Comment by HugoDF** [comment]
I can revive it

I think the biggest issue was added bulk from that but if we just do string merging it should be ok.

**Comment by calebporzio** [comment]
Ok, I think Alpine should force x-show to override any :show bindings.

Is there a simple way to accomplish this without digging into the object syntax support (which I think we will likely end up adding after all)?

**Comment by HugoDF** [comment]
Well the only bit from that PR that we would need is the "style rule merging", _or_ we can just order the operations so that `style` binding runs first and `x-show` second, always.

**Comment by HugoDF** [comment]
Closing since we're going to order the things

**Pull request closed without merging**
