### PR TITLE
Debounce plugin

### PR DESCRIPTION
**Pull request by tanthammar**
Plugin that adds a magic $debounce directive

### CODE REVIEW

**Comment by tanthammar** [comment]
Example

```html
<div x-data="{
    foo(text) {
        $debounce(() => console.info(text), 500)
    }
}">
    <button @click="foo('Hello')"></button>
</div>
```

**Comment by SimoTod** [comment]
It doesn't seem to work for me, every time alpine evaluates $debounce, it returns a new callback and timeoutId is always undefined so each click triggers the function. It's probably worth adding some tests to make sure it works now and in the future.

Also, it's worth asking Caleb if he's willing to accept it into the core first.

**Comment by tanthammar** [comment]
Thank you for the feedback. 

This, and the throttle PR, are more like feature requests for something that I would like in the core. 

I am hoping that someone with better knowledge of Alpine can improve it so Caleb can consider to pull it in. 

Or, if there is a better way to get these directives.

**Comment by calebporzio** [comment]
Thanks Tina, going to hold off on this for now though - thanks for contributing!

**Pull request closed without merging**
