### PR TITLE
fix: add git url to all package.json's

### PR DESCRIPTION
**Pull request by jasikpark**
This would help services like renovatebot and dependabot find the changelog for each package when creating package update PR's - I'd appreciate it if that was possible!

### CODE REVIEW

**Comment by calebporzio** [comment]
Hi @jasikpark - can you expound on the benefit this provides?

**Comment by jasikpark** [comment]
An example is https://github.com/jasikpark/jasik-xyz/pull/321 — it’s an autogen dependency upgrade PR upgrading prettier for my website, and it’s able to find the prettier changelog because the repository key is set.

I just merged this change to https://snowpackjs/astro/ so I’ll A update to improve the syntax adding a `directory` key and B test whether the addition of the key achieves the effect I want.

Caleb Jasik
***@***.***
https://jasik.xyz

On June 16, 2021 at 8:52:02 AM, Caleb Porzio ***@***.***) wrote:

Hi @jasikpark - can you expound on the benefit this provides?

**Comment by jasikpark** [comment]
renovatebot seems to have problems detecting nested changelogs for me at the moment, hopefully I can figure out what's up with it... https://github.com/renovatebot/renovate/issues/4724#issuecomment-862681819

**Comment by calebporzio** [comment]
I'm sorry, I don't understand the direct value this provides to this repo, so I'm closing this. Also VueJS doesn't have this listing in their root package.json at least - so that signals to me that it's not necessary.

Thanks for being willing to contribute though!

**Comment by jasikpark** [comment]
To explain a bit better, https://github.com/jasikpark/live.collegemusic.co.uk/pull/155#event-4912597783 is a PR to upgrade my `alpine` dependency, and normally I would be able to read the changelog in the PR.

It doesn't show mainly because it looks in the github repo to find the changelog, and without the repository key in the `package.json` it doesn't know what repository the package came from.

**Pull request closed without merging**
