### PR TITLE
fix(morph): currentNode can also be null, not just undefined, fixes #3728

### PR DESCRIPTION
**Pull request by levu42**

### CODE REVIEW

**Comment by ekwoka** [comment]
#3762

**Comment by joshhanley** [comment]
@levu42 thanks for the PR! Any chance you could add a test for this? Thanks!

**Comment by levu42** [comment]
@joshhanley not easily, since, as I described in #3728 I can't reproduce it in a minimal test case. I have it happen in a bigger Livewire project, but my tries to make a minimal test case weren't successful so far.

**Comment by joshhanley** [comment]
@levu42 yeah I just tried too, and couldn't replicate it using morph alone outside of a Livewire context.

**Comment by calebporzio** [comment]
Thanks!

**Pull request merged**
