### PR TITLE
Alpine.js HTML compat build with `data-alpine-*` attributes (instead of `x-*`)

### LINKED ISSUE #464: Alternative binding  for directives?
Hey,

I wonder if it is possible to specify a custom directive (e.g data-x-data instead of x-data). I am having trouble of implementing Alpinejs in Salesforce lightning framework.

### PR DESCRIPTION
**Pull request by HugoDF**
Closes #464 

- new rollup config that replaces `x-` with `data-alpine`.
- new built JS output

### CODE REVIEW

**Comment by HugoDF** [comment]
Relevant comments from the other PR

https://github.com/alpinejs/alpine/pull/506#issuecomment-632836336
https://github.com/alpinejs/alpine/pull/506#issuecomment-634162527

**Comment by calebporzio** [comment]
Thanks @HugoDF, maybe there was a miscommunication. I thought we settled on NOT addressing this.

Anyhow, thanks for the PR, it will be useful if we do eventually want to support data- attrs, but I think for now this isn't a real tangible issue for anyone that I'm aware of (with the exception of the LWC case, but I believe that wouldn't work anyways.)

Closing for now unless I'm missing something. Thanks!

**Comment by HugoDF** [comment]
👍 happy with that too, this is trivial to revive later in any case

**Comment by THS-on** [comment]
@calebporzio I want to use Alpine.js with [Pandoc](https://pandoc.org/) to add some Interactive elements to a automatically generated Website. Pandoc prefixes all user specified attributes with `data-` which makes it not easily possible to use Alpine.js without some post processing.

I'm currently testing this version and it works really well for my use case. It would be great to have official support for that.

**Comment by Natetronn** [comment]
@calebporzio With all due respect, I think you may be missing something? Here's some of my thoughts on the subject:

https://github.com/alpinejs/alpine/pull/506#issuecomment-698430006 

And consider reading @tomhodgins thoughts a few replies above my own, if you haven't already.

@HugoDF pointed out the PR (thanks for that) but, please add my vote for this to be added officially.

Thanks you!

**Pull request closed without merging**
