### PR TITLE
IE11 template polyfill issue leads to false warnings

### LINKED ISSUE #714: Invalid multiple element root error on IE11
I'm not sure if I am doing something wrong, but for some reason every `x-for` on IE causes the following warning to be shown in the console even though I only have one child node in my loop.  The error is not displayed in Chrome.

```
Alpine: <template> tag with [x-for] encountered with multiple element roots. Make sure <template> only has a single child node.
```

I can replicate the problem even with a very basic application like this:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <script
            type="module"
            src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.6.0/dist/alpine.min.js"
        ></script>
        <script
            nomodule
            src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.6.0/dist/alpine-ie11.min.js"
            defer
        ></script>
    </head>
    <body>
        <div x-data="test()">
            <template x-for="link in links">
                <div>
                    <span x-text="link.name"></span>
                </div>
            </template>
        </div>
        <script>
            function test() {
                return {
                    links: [
                        {
                            name: 'link1',
                        },
                        {
                            name: 'link2',
                        },
                    ],
                };
            }
        </script>
    </body>
</html>
```

### PR DESCRIPTION
**Pull request by HugoDF**
Closes #714 

- Switch to el.content.childNodes.length as per @ryangjchandler suggestion

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@HugoDF nice one 🤙🏼

**Comment by ryangjchandler** [comment]
@HugoDF did you run this through on IE at all?

**Comment by HugoDF** [comment]
> @HugoDF did you run this through on IE at all?

Nope, I don't have IE handy 👀

**Comment by ryangjchandler** [comment]
> Nope, I don't have IE handy 👀

Okay, I'll use your branch as the CDN and test it out on IE to see if it's all good.

**Comment by HugoDF** [comment]
@ryangjchandler done

**Comment by ryangjchandler** [comment]
Nice one, I'll test this in a bit. FWIW, I put up a little HTML tester (https://previewer.ryangjchandler.co.uk) for easy testing in different browsers, specifically IE11 because CodePen and others dont' support IE.

**Comment by ryangjchandler** [comment]
@HugoDF - I tested this and it still shows that same error.. I'm wondering if there is something else that we can use..

**Comment by HugoDF** [comment]
> @HugoDF - I tested this and it still shows that same error.. I'm wondering if there is something else that we can use..

Ok we could just strip the warning for IE11?

**Comment by HugoDF** [comment]
Converting to draft until I add the IE11 stripping comments to the warning function

**Comment by SimoTod** [comment]
according to MDN, safari could have issues as well since it's not supported for documentFragment -> https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/childElementCount

**Comment by SimoTod** [comment]
childNodes is supported but it contains all nodes (including text nodes if you have spaces and stuff like that in between tags).
i think we can wither include the polyfill (https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/childElementCount#Polyfill_for_IE8_IE9_Safari) ot just apply the same logic to the check (looping on all nodes and counting the ones that are real elements)

**Comment by calebporzio** [comment]
I say we add the polyfill. The less we change the actual source for IE11 the better.

**Comment by calebporzio** [comment]
Also, like Simone said, childNodes includes non-element nodes, so we should avoid that.

**Comment by HugoDF** [comment]
Put it back to `childElementCount` and added the polyfill for IE11 🙂

**Comment by calebporzio** [comment]
Great, thanks Hugo!

**Pull request merged**
