### PR TITLE
Fix $watch scope, Support nested properties, Support watch deep

### PR DESCRIPTION
**Pull request by ahmedkandel**
Replaces #292

### CODE REVIEW

**Comment by ahmedkandel** [comment]
Here is a codepen to cover watch cases:
https://codepen.io/tomorrowsystem/pen/BaNPpXz?editors=1001

**Comment by ahmedkandel** [comment]
It may need some refactoring, While it will not be easy to get rid of recursive iterations.

**Comment by ahmedkandel** [comment]
What do you think guys? Is this updated implementation better?
@calebporzio @HugoDF @SimoTod

**Comment by calebporzio** [comment]
I'm going to close this for now and only support shallow "watching" in Alpine V2. I believe this feature will just work out of the box with the new v3 reactivity engine.

I know this wasn't an easy implementation, so thank you for the contribution 🙏

**Comment by justingolden21** [comment]
How many months or years has this been? I still can't watch an object? How am I supposed to react to changes to the object? DO I need to attach a listener to literally every single item in the UI that is bound to any part of the object? Doesn't seem productive for a JS framework. Makes many, many UIs impractical if not impossible to write.

**Comment by ryangjchandler** [comment]
@justingolden21 You can use `Alpine.effect()` as mentioned in my comment above.

**Pull request closed without merging**
