### PR TITLE
Create alpine.d.ts

### PR DESCRIPTION
**Pull request by zoeleu**
Linked to my recent issue #2199 

This is untested and may be wrong, please correct the code if it is.

### CODE REVIEW

**Comment by danddanddand** [comment]
I think this would need to be fleshed out a lot more before being added. As an example, this is the alpine.d.ts file from our project (and I know it's not complete).

You are welcome to build on this. 

```
type AlpineWatch = ( targetProperty: string, callback: ( ( newValue: any, oldValue?: any ) => void ) ) => void;

type AlpineMagicProperties<AlpineGlobalStore = Record<string, V>> = {
    $el?: HTMLElement;
    $refs?: { [xRefId: string]: HTMLElement };
    $watch?: AlpineWatch;
    $nextTick?: ( functionToCall: ( () => void ) ) => void;
    $store?: AlpineGlobalStore;
    $dispatch?: <T = any>( eventName: string, eventDetail?: T ) => void;
};

type AlpineMandatoryProps = {
    init?: () => void,
}

declare type AlpineComponent<Props extends BaseAlpineProps, AlpineGlobalStore = {}> = {
    ( ...args: any[] ): AlpineMandatoryProps & Props & AlpineMagicProperties<AlpineGlobalStore>;
};

interface BaseAlpineProps {
    init?: ( () => void ) | ( () => Promise<void> );
}

interface AlpineRoot {
    store,
    start,
    directive,
    version: string,
}

declare module "alpinejs" {
    type AlpineDirectiveCallback = ( p1 : HTMLElement, p2 : any, p3: any ) => void;
    type AlpineRootCallback = ( ( alpineRoot : Alpine ) => void );
    function store<R>( storeName: string, value : R ) : void;
    function store<R>( storeName: string ) : R;
    function directive( directiveName : string, cb : AlpineDirectiveCallback );
    function plugin( alpineRootCallBack : AlpineRootCallback ) : void;
    function data( dataName: string, dataInitializer: () => Record<string, V> ): void;
    function effect( effectCallback: () => void ): void;
    function reactive<T>( initialData: Record<string, T> ): Record<string, T>;
    function magic( magicName: string, callback: ( el: HTMLElement, alpineObj: { Alpine: Alpine } ) => any ): void;
    function start() : void;
    function raw( v : any ) : any;

    export default Alpine = {
        version: string,
        store,
        start,
        directive,
        plugin,
        data,
        effect,
        reactive,
        magic,
        raw
    };

}
```

I had created small fork to convert Alpine to TS just to generate types file (and since it uses Vue reactivity engine which is all TS and main Alpine dependancy it was pretty easy) but I haven't had time to circle back to it.

**Comment by danddanddand** [comment]
I agree @ryangjchandler. I liked converting it to TS and majority of changes merge in nicely as Alpine gets updated. It was really easy because Alpine uses esbuild and reactivity definitions basically inherited from Vue, I just didn't have time to finish it. For our project definition above has been good enough but it could be much better. I would love to see your version to see what could be added/improved if you don't mind sharing.

**Comment by wtho** [comment]
@ryangjchandler @danddanddand 

I gave it a shot and created a PR on definitelytyped:
DefinitelyTyped/DefinitelyTyped#58130

I have to wait for this DefinitelyTyped-tools PR to be merged to reuse types from @vue/reactivity:
microsoft/DefinitelyTyped-tools#376

Anyway, in the meantime it would be great if some of you could review or even share ownership of the types with me. I am open for improvements in the types. As the typescript-bot in the PR phrases it:

> :bell: @wtho — you're the only owner, but it would still be good if you find someone to review this PR in the next few days, otherwise a maintainer will look at it. (And if you do find someone, maybe even recruit them to be a second owner to make future changes easier...)

Cheers!

**Comment by arcanemachine** [comment]
Did this ever get resolved?

**Pull request closed without merging**
