### PR TITLE
Check for existence of parent component first when filtering mutations

### PR DESCRIPTION
**Pull request by thormeier**
Suppresses an error caused by the parent component being null in some
cases.

Fixes https://github.com/alpinejs/alpine/issues/90.

### CODE REVIEW

**Comment by calebporzio** [comment]
Hey @thormeier - what are the cases where it's null?

**Comment by thormeier** [comment]
See https://github.com/alpinejs/alpine/issues/90 - I wasn't able to fully understand the interdependence between Choices and Alpine, but I'm almost sure it happens when the mutation target is removed from the DOM before the observer is triggered. That's at least what my observation yielded.

**Comment by joedixon** [comment]
I should have read through the PRs first, but I just ran into this same problem and raised and issue #110 

I get a similar issue when I have the WhatFont Chrome extension enabled.

**Comment by joedixon** [comment]
I should have read through the PRs first, but I just ran into this same problem and raised an issue #110 

I get a similar issue when I have the WhatFont Chrome extension enabled.

**Comment by joedixon** [comment]
I should have read through the PRs first, but I just ran into this same problem and raised an issue #110 

I get a similar issue when I have the WhatFont Chrome extension enabled.

**Comment by joedixon** [comment]
I should have read through the PRs first, but I just ran into this same problem and raised an issue #110 

I get a similar issue when I have the WhatFont Chrome extension enabled.

**Comment by joedixon** [comment]
I should have read through the PRs first, but I just ran into this same problem and raised an issue #110 

I get a similar issue when I have the WhatFont Chrome extension enabled.

**Comment by joedixon** [comment]
I should have read through the PRs first, but I just ran into this same problem and raised an issue #110 

I get a similar issue when I have the WhatFont Chrome extension enabled.

**Comment by joedixon** [comment]
I should have read through the PRs first, but I just ran into this same problem and raised an issue #110 

I get a similar issue when I have the WhatFont Chrome extension enabled.

**Comment by joedixon** [comment]
I should have read through the PRs first, but I just ran into this same problem and raised an issue #110 

I get a similar issue when I have the WhatFont Chrome extension enabled.

**Comment by ryatkins** [comment]
+1 Get this error as well.  Running Chrome in Incognito Mode fixes the issue.

**Comment by calebporzio** [comment]
Thanks @thormeier.

Any chance you can write a test that simulates this behavior? I merged it, but because no test will fail if I roll it back - it could be refactored out in the future and the error could crop back up again.

Thanks.

**Comment by thormeier** [comment]
@calebporzio Sure thing, will do a follow-up PR on this.

**Comment by thormeier** [comment]
@calebporzio Added a test here: https://github.com/alpinejs/alpine/pull/126

**Pull request merged**
