### PR TITLE
Remove stale event handlers when nodes are readded to the document.

### PR DESCRIPTION
**Pull request by cthulahoops**
Fixes: #1171

I'm not familiar enough with the project to know what I need to do to test this or if it's the right approach, but it does appear to resolve the problem for my simple example.

### CODE REVIEW

**Comment by HugoDF** [comment]
@cthulahoops you can add a test with your example from the issue in the `for.spec.js` file I think

**Comment by cthulahoops** [comment]
`for.spec.js` rather than `on.spec.js`?

**Comment by HugoDF** [comment]
> @HugoDF `for.spec.js` rather than `on.spec.js`?

Oops yeah sorry `on.spec.js`

**Comment by cthulahoops** [comment]
At the top of `on.spec.js` we replace the `MutationObserver`with an empty class so the bug doesn't happen in the tests. It looks like the tests still pass if I remove that.

**Comment by HugoDF** [comment]
> At the top of `on.spec.js` we replace the `MutationObserver`with an empty class so the bug doesn't happen in the tests. It looks like the tests still pass if I remove that. That is the existing tests pass, and it becomes possible to write a test to reproduce my bug.

That makes a lot of sense.

Are you saying you can write a failing test if mutation observer isn't faked? As far as I remember, I don't think the mutation observer works properly in tests, it's not implemented 1-1 with browsers.

I think I've seen other tests where we "fake" the mutation observer triggering, that might be an option as well.

**Comment by cthulahoops** [comment]
Yes! I can write the failing test, so the mutation observer works well enough for this test at least.

I can't get the passing test to run locally. It seems to be refusing to run my changed code, it just runs the original whatever I do. It seems to run and pass here though.

**Comment by HugoDF** [comment]
> Yes! I can write the failing test, so the mutation observer works well enough for this test at least.
> 
> I can't get the passing test to run locally. It seems to be refusing to run my changed code, it just runs the original whatever I do. It seems to run and pass here though.

Yeah for it to work locally you need to rebuild the files (& maybe link? I forget)

If they're working here it's good enough though 🙂

**Comment by cthulahoops** [comment]
This branch is working well for me. Is there anything else needed?

**Comment by calebporzio** [comment]
Thanks for the contribution.

For me to feel comfortable merging I will need a more clear and succinct explanation/demonstration of the problem. Ideally without needing to understand LiveView or morphdom.

**Comment by HugoDF** [comment]
@calebporzio I think this sample code illustrates it pretty well

https://github.com/alpinejs/alpine/issues/1171#issuecomment-798204177

Might be an edge case for Alpine by itself (I'm not sure why you would reinsert existing Nodes with Alpine) but might cause issues with libraries that attempt to reuse DOM nodes?

**Comment by cthulahoops** [comment]
I expect you'd encounter this issue in pure alpine in applications that involve reordering a list. I can imagine a todo list that allows the user to drag and drop nodes to order them. I was also working on an (unrelated) app with a list of conversations and conversations moved to the top of the list when new messages arrive, which I think would have triggered this issue if it were in alpine.

I do agree this is going to be a more common problem when using liveview or the like. I ran into it with a multi-input box for entering e-mail addresses. The container has a div for each e-mail address and then an input box at the end. When you add a new e-mail address, liveview readds all the elements in the correct order - including the input box.

It's not too hard to restructure things to work around this problem if you understand it, but it's very confusing and hard to understand.

The bug occurs because MutationObserver doesn't tell you whether a node is being added for the first time or re-added, so alpine will always add the event handler even if it was there already. I think removing stale event handlers is the correct fix rather than trying to detect readded nodes in order to avoid re-adding the event handlers. This way things should continue to work if event handlers are added or removed from nodes.

Is that helpful? I'm happy to try and explain further.

**Comment by calebporzio** [comment]
Thanks for the reference @HugoDF 

Yeah, this makes sense. I ran into this when re-implementing the mutation observer for V3 of Alpine.

Here's the implementation I came up with: 
image

Seeing as this will be fixed in the next version in a more ideal way, I think I'm comfortable pulling this in for now. Thank you!

**Comment by cthulahoops** [comment]
:tada: :smile: 

I think replacing the callback with the new one in this case is likely to be more correct than skipping.

For example, I have code that looks a bit like this:

```
<ul x-data="active = 0">
<%= for {suggestion, idx} <- Enum.with_index(@suggestions) do %>
   <li x-bind:mouseover="active = <%= idx %>" id="suggestion-<%= suggestion.id %>">
<% end %>
</ul>
```

When suggestions are added or removed the index of each element changes, and the callback needs replacing. I could implement this in lots of ways to avoid this, but I think things are likely to get confusing if callbacks aren't updated.

Thanks for merging!

**Pull request merged**
