### PR TITLE
Option to set custom listener manipulation (e. g. jQuery events compatibility) 

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
This change would allow to enable compatibility with jQuery event system

```javascript
document.addEventListener('alpine:init', () => {
  Alpine.setListenerManipulators(
    (target, event, handler, options, modifiers) => { $(target).on(event, handler) },
    (target, event, handler, options) => { $(target).off(event, handler) }
  )
})
```

### CODE REVIEW

**Comment by philwolstenholme** [comment]
I think this might be better off as a third-party plugin, then people who need it can use it, and people that don't need it won't need to increase Alpine's complexity and size unnecessarily.

https://alpinejs.dev/advanced/extending
https://alpinejs.dev/advanced/extending#writing-and-sharing-plugins

**Comment by MartinMystikJonas** [comment]
Example usage/test that uses this feature to make Alpine compatible with jQuery events:

```html
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
        <script src="//unpkg.com/alpinejs" defer></script>
        <script>
            document.addEventListener('alpine:init', () => {
                Alpine.setListenerManipulators(
                    (target, event, handler, options, modifiers) => { $(target).on(event, handler) },
                    (target, event, handler, options) => { $(target).off(event, handler) }
                )
                $("span").trigger("click")
            })
        </script>

        <div x-data="{val: 'old'}">
            <span @click="val='new'" x-text="val"></span>
        </div>
```

**Comment by calebporzio** [comment]
Thanks for contributing this. In order to keep Alpine's API surface area slim I think I'm going to reject this addition. Unless there is a large enough demand from the community - if that is the case, please re-open with references to those conversations.

**Comment by MartinMystikJonas** [comment]
I fully understand need to keep API as slim as possible. But I believe that many people would like to use Alpine alongside jQuery and existing jQuery plugins. It is mostly possible but event system incompatibilities are unexpected and not easy to solve.

There are examples of some questions about Alpine and jQuery compatibility:
https://github.com/alpinejs/alpine/issues/264
https://stackoverflow.com/questions/66592950/can-i-write-both-alpine-js-and-jquery-in-same-project-will-it-cause-any-documen

For some jQuery plugins event systems incompatibility can be solved by manually adding listeners and proper reactions thet pass changes to Apline so x-model can by simulated at least partially this way. There is good example how it can be done for select2 https://codewithhugo.com/alpinejs-jquery-plugin-integration-select2/

But some people struggle to make these work because they do not know about need to made these manual event listeners to allow Apline to react to events triggered by jQuery plugins: https://codepen.io/pcohen12/pen/VwvmboW

And for many jQuery plugins this is not easily possible without creating custom fork that triggers native events instead of jQuery events.

People trying use Alpine and jQuery events was mentioned few times:
https://github.com/alpinejs/alpine/issues/310#issuecomment-617696162
https://github.com/alpinejs/alpine/discussions/1131
https://github.com/alpinejs/alpine/discussions/694#discussioncomment-48375
https://github.com/alpinejs/alpine/issues/402#issuecomment-617380302

I also discussed my problem with @SimoTod here: https://github.com/alpinejs/alpine/discussions/2062 where he suggested some workarounds but I think some universal solution would be nice to have in Alpine itself instead of hacking it for every event in every jQuery plugin used.

I hope this would be enough for you to reconsider this PR, but I understand that it might be just small part of Apline users who needs to make it fully jQuery and jQuery plugins compatible so you would reject this to prevent bloating Apline API.

**Comment by MartinMystikJonas** [comment]
@calebporzio Just another idea: How about detecting existence of window.jQuery and automatically switching to jQuery event listeners if jQuery is available?

**Comment by dee-ene-gee** [comment]
@MartinMystikJonas My suggestion would be to create a custom directive to handle jQuery events separately, like so:
[https://jsfiddle.net/805w19vj/1/](https://jsfiddle.net/805w19vj/1/)

Overriding the default `x-on` directive with a custom directive named `on` also seems to work, including the shorthand `@` syntax, though this would require writing your own modifier functionality:
[https://jsfiddle.net/9283twqa/1/](https://jsfiddle.net/9283twqa/1/)

I copied the structure of the default [x-on.js](https://github.com/alpinejs/alpine/blob/main/packages/alpinejs/src/directives/x-on.js) directive.

**Comment by MartinMystikJonas** [comment]
@dee-ene-gee I was thinking about this first but there is significant amout of logic hidden in Alpine ```on``` implementation that would need to be reimplemented: https://github.com/alpinejs/alpine/blob/f5d2857a88c7dcf48e981e16619a8d6c3265ebcd/packages/alpinejs/src/utils/on.js

**Comment by f-liva** [comment]
Thank you @dee-ene-gee your solution was perfect!

Maybe it's possible to extend the native x-model directive and supporto also this with jQuery?

**Comment by ekwoka** [comment]
I don't think it's going to happen.

It's like asking for IE9 support.

**Pull request closed without merging**
