### PR TITLE
Add enhancement for discusssion #3293

### PR DESCRIPTION
**Pull request by puckowski**
* Add watch enhancement for discussion #3293.

### CODE REVIEW

**Comment by puckowski** [comment]
CodePen with cdn.min.js from main_3293 forked from https://codepen.io/dinyo/pen/eYVaKgj?editors=1111 https://codepen.io/puckowski/pen/poQJzzv?editors=1111

**Comment by ekwoka** [comment]
I think it could be beneficial to check for and prefer `structuredClone`.

Maybe set this up more as a polyfill type thing.

At script init do something like `const deepClone = globalThis.structuredClone ?? customClone`

So we can prefer the future :)

**Comment by puckowski** [comment]
When ```structuredClone``` encounters a proxy object, it throws a ```DataCloneError``` and fails to clone the object.

I ran into ```DataCloneError``` issues when I was using ```structuredClone``` for https://github.com/alpinejs/alpine/pull/3046

This presented issues as there is no great way to tell if an object is proxied in JavaScript, thus I had to support a simple shallow clone implementation along with ```structuredClone```. There were concerns about the number of lines added with 3046.

Plus, depending on how many browser versions the Alpine user wishes to support, they may need to polyfill ```structuredClone``` (https://caniuse.com/?search=structuredClone). Or, we add the ```structuredClone``` polyfill to Alpine for all users at the expense of bundle size. Again, that may not be ideal in terms of number of lines added.

I think 3617 as is allows users of Alpine to reliably get the old and new value with $watch with few lines of code added while passing tests.

**Comment by calebporzio** [comment]
Thanks for the PR - I'm wondering if we can just use the simple JSON.parse(JSON.stringify(...)) clone method

It obv won't keep functions around, but I think it's ok to have that as a limitation when accessing "old" right?

**Comment by ekwoka** [comment]
Is there risk of circular references?

**Comment by calebporzio** [comment]
Thanks for contributing!

In order to keep this project as focused and maintainable as possible, I'm going to close this pull request.

This isn't "no", it's just "no for now".

If you disagree, or there's further demand from the community, please re-open this PR and we'll reconsider!

**Comment by Suall1969** [comment]
This PR and #3046 were both closed, but the relevant documentation section on [Deep watching](https://alpinejs.dev/magics/watch#deep-watching) still falsely states that the old value is accessible.
It turns out you can access the old value if you define a getter that clones the property and watch that instead. This way the nuances of the cloning algorithm can be altered per requirements, though in most cased a shallow clone would suffice:
```js
<div x-data="{ foo: { bar: 'baz' }, get fooCopy() { return { ...this.foo } }}" x-init="$watch('fooCopy', (value, oldValue) => console.log(value, oldValue))">
    <button @click="foo.bar = 'bob'">Update</button>
</div>
```

**Pull request closed without merging**
