### PR TITLE
Escaping RegExp from Proxy

### PR DESCRIPTION
**Pull request by amrikasir**
when I using regex test or regex exec `this.condition.regex.test('example'),` I've got `RegExp.prototype.exec called on incompatible receiver [object Object]`

if anyone have a better idea, I hope for some advices

### CODE REVIEW

**Comment by SimoTod** [comment]
Good point @amrikasir , but we can't bind target for every function because the component would partially lose its reactivity.
Your best option is to check if target is an instance of RegExp and in that case applies your patch.
Instead of doing it in the getter, it probably makes more sense to do something in util > deepProxy (so if the type is RegExp you won't wrap it in a Proxy).

**Comment by amrikasir** [comment]
@SimoTod when do it in utils > deepProxy, it wont wrap in Proxy. it mean, it won't reactive when we want to change patterns. what if we check the instanceof target in component > wrapDataInObservable ?

**Comment by SimoTod** [comment]
@amrikasir
Possibly but I believe that RegExp is immutable so you are actually creating a new instance and assigning it to the parent object which is still a proxy.
I'm typing it from the top of my head so I might be wrong, maybe an example would help. 
You probably need to test a few solutions and see which one works without bugs.

**Comment by amrikasir** [comment]
sure, I'll. I hope that a better idea for this issue. thanks @SimoTod

**Comment by amrikasir** [comment]
@SimoTod it works in Util or in Component, so I put it in Util like you said.

it works :smiley:

**Comment by SimoTod** [comment]
Sorry, I know it was my suggestion but we probably need a better and more generic solution since Date objects have the same problem (see #206) and there was an old issues about Promises (#161) which is the same issue again. Given that it will likely apply to other native object types, I don't think it's a good idea to add an if for each type any more. 
Also, Date objects have setters method (i.e. setSeconds()) which should probably be reactive.
Any thoughts?

**Comment by tlgreg** [comment]
What should be deep proxied btw?

Currently, some native objects are blacklisted, but otherwise, the conditions letting through any object.

My first thought was to do a plain object check, but that also excludes arrays, which are deep-proxied atm (could be an exception).

Also, the current conditions letting through things like `Map` and `Set` instances too, but their items are not available as enumerable props so the `for ... in` loop does nothing.

**Comment by SimoTod** [comment]
@tlgreg It's an option, we could use Proxies only for plain objects `{}` and Arrays.
The only issue here is that if the object has a setXXX method and you call it, it won't update the component which may or may not be confusing.

For example, assuming that only plain objects are wrapped in a proxy
```html
<div x-data="{ foo: new Date() }">
  <span x-text="foo"></span>
  <button @click="foo.setDate(foo.getDate() + 1)">+</button>
  <button @click="foo.setDate(foo.getDate() - 1)">-</button>
</div>
```
clicking + and - won't update the content of `<span>`.

Good point about Map and Set, they should probably work as Array does. 
I think we need a different issue/PR for this but it's probably doable with checking if an object is iterable and using `for ... of` or some similar approach.

**Comment by SimoTod** [comment]
An alternative would be to use the 'apply' Proxy trap to catch the method call, bind it to the right context and trigger a component refresh. (something like https://github.com/alpinejs/alpine/compare/master...SimoTod:feature/native-objects?expand=1 https://codepen.io/SimoTod/pen/jOPmoeN).
There is a small performance impact because methods that don't change the object state will trigger a pointless refresh but I'm not sure we can avoid it.

**Comment by amrikasir** [comment]
I think we can make it generic..

we should escaping every object when it is instanceof it's contructor

```javascript
// checking RegExp
/[a-z]+/ instanceof /[a-z]+/.constructor // true

// checking Date Type
var dateWithNew = new Date()
var datewithoutNew = Date()

datewithoutNew instanceof datewithoutNew.constructor // false
dateWithNew instanceof dateWithNew.constructor // true

// checking Promise
var ObjectPromise = new Promise(() => {})
ObjectPromise instanceof ObjectPromise.constructor // true
`

what should we do just escaping it from Proxy ??
how about that ?

**Comment by amrikasir** [comment]
btw, I just test instanceof checking in browser console.

**Comment by calebporzio** [comment]
Thanks for this, but it should be fixed with the new reactivity core in v2.1.0

**Pull request closed without merging**
