### PR TITLE
Multiple enhancements and fixes for `collapse` plugin.

### PR DESCRIPTION
**Pull request by grey4owl**
- Added horizontal (width) collapse modifier `.horizontal` https://github.com/alpinejs/alpine/discussions/2809
- Fixed preserved overflow issue and added optional modifier for that `.overflow` https://github.com/alpinejs/alpine/discussions/2207
- Changed overflow `hidden` to `clip`  https://github.com/alpinejs/alpine/discussions/3948

### CODE REVIEW

**Comment by simonferndriger** [comment]
Is there currently a merging issue? Is that the reason that this enhancements have not been released yet?

**Comment by ekwoka** [comment]
Well, it isn't passing the collapse tests, or seem to have added any tests to validate this behavior either.

**Comment by calebporzio** [comment]
Thanks for these contributions, we will need tests though to consider them so we ensure nothing breaks for people. Please re-submit with tests and we can look deeper. Also separate them out into individual PRs so we can merge or close individually.

Thanks

**Comment by SpyridonLaz** [comment]
that is a great idea for collapsing columns in lists. if @grey4owl could develop this further it would be really appreciated.

**Comment by grey4owl** [comment]
Heey, thanks for the responses! :]

I will try to do this during the weekend because otherwise I don't have much free time. I did this for my own needs a month ago and built via bun. If someone wants to test it before it is merged, you can copy code below and try it for yourself..

```javascript
var L=function(C,$,g){if(C.indexOf($)===-1)return g;const x=C[C.indexOf($)+1];if(!x)return g;if($==="duration"){let R=x.match(/([0-9]+)ms/);if(R)return R[1]}if($==="min"){let R=x.match(/([0-9]+)px/);if(R)return R[1]}return x};function J(C){C.directive("collapse",$),$.inline=(g,{modifiers:x})=>{let R=x.includes("overflow")?!0:!1;if(!x.includes("min"))return;if(g._x_doShow=()=>{},g._x_doHide=()=>{},R)g.style.overflow="clip"};function $(g,{modifiers:x}){let R=L(x,"duration",250)/1000,q=L(x,"min",0),E=!x.includes("min"),z=x.includes("horizontal")?"horizontal":"vertical",M=x.includes("overflow")?!0:!1;if(!g._x_isShown)g.style.height=`${q}px`;if(!g._x_isShown)g.style.width=`${q}px`;if(!g._x_isShown&&E)g.hidden=!0;if(!g._x_isShown)g.style.overflow="clip";let N=(I,G)=>{let B=C.setStyles(I,G);if(z==="vertical")return G.height?()=>{}:B;else return G.width?()=>{}:B},K={transitionProperty:"width, height",transitionDuration:`${R}s`,transitionTimingFunction:"cubic-bezier(0.4, 0.0, 0.2, 1)"};g._x_transition={in(I=()=>{},G=()=>{}){if(E)g.hidden=!1;if(E)g.style.display=null;let B,D;if(z==="vertical")B=g.getBoundingClientRect().height,g.style.height="auto",D=g.getBoundingClientRect().height;else B=g.getBoundingClientRect().width,g.style.width="auto",D=g.getBoundingClientRect().width;if(B===D)B=q;C.transition(g,C.setStyles,{during:K,start:z==="vertical"?{height:B+"px"}:{width:B+"px"},end:z==="vertical"?{height:D+"px"}:{width:D+"px"}},()=>g._x_isShown=!0,()=>{if(Math.round(g.getBoundingClientRect().height)==Math.round(D)||Math.round(g.getBoundingClientRect().width)==Math.round(D)){if(!M)g.style.overflow=null}})},out(I=()=>{},G=()=>{}){let B=z==="vertical"?g.getBoundingClientRect().height:g.getBoundingClientRect().width;C.transition(g,N,{during:K,start:z==="vertical"?{height:B+"px"}:{width:B+"px"},end:z==="vertical"?{height:q+"px"}:{width:q+"px"}},()=>g.style.overflow="clip",()=>{if(g._x_isShown=!1,g.style.height==`${q}px`&&E||g.style.width==`${q}px`&&E)g.style.display="none",g.hidden=!0})}}}}document.addEventListener("alpine:init",()=>{window.Alpine.plugin(J)});

```

**Comment by marchershey** [comment]
Hey @grey4owl, do you have an updated ETA on when you can get this testing so @calebporzio can get this pushed? I would really appreciate it!

**Pull request closed without merging**
