### PR TITLE
allow await in invalid expression wrapper

### PR DESCRIPTION
**Pull request by ekwoka**
Solves: https://github.com/alpinejs/alpine/discussions/3118

Problem: expressions that are identified as invalid right hand expressions are wrapped in an IIFE, which brakes any `await` calls.

Solution: make IIFE async

Expressions are normally treated as async functions, but this was one situation in which they were not.

### CODE REVIEW

**Comment by joshhanley** [comment]
@ekwoka have pushed an empty commit to trigger CI, as I think the failing test is unrelated, but just want to make sure

**Comment by joshhanley** [comment]
@SimoTod if you get the chance, can you comment on Caleb's concern above?

**Comment by ekwoka** [comment]
It shouldn't change the behavior for anything else, in this case.

Async functions, when called, run synchronously up to the first await, and then the resolution is handled in the queue, but the promises from the outer `AsyncFunction` and this inner `async()={}` should virtually collapse together.

**Comment by joshhanley** [comment]
Yep makes sense to me. Thanks for the PR!

**Pull request merged**
